In [24]:
import numpy as np  #package

In [26]:
random_array = np.random.rand(3,3)
#3*3 array of random floats between 0 and 1
np.sum(random_array)
print(random_array)

[[0.7146867  0.67572853 0.33519366]
 [0.96815033 0.41354444 0.48543938]
 [0.38415944 0.85456534 0.89052332]]


In [ ]:
#import staements

In [28]:
#import a specific function
from math import sqrt
print(sqrt(16))

4.0


In [30]:
#import a package or module with alias

import numpy as np
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [32]:
#whole module

import math 
result = math.sqrt(45)
print(result)

6.708203932499369


In [34]:
#import everything present in module or package

from math import*

In [36]:
#import a function from a submodule

from numpy.random import rand

In [38]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']
