# Module6: NumPy

In [18]:
# Mode 1  Read only 
with open('module5.txt', 'r') as file: 
    content = file.read()
    #print(content)
    file.seek(0)
    print("Reading line by line")
    print(file.readline())
    print(file.readline())

    file.seek(0)
    print("Reading all lines")
    #print(file.readlines())

# Mode2 r+ read & write 
file2 = open('module5.txt','r+')
file2.write("Hola")
print(file2)
file2.close()

# Mode3 a append 
file3 = open('module5.txt', 'a')
file3.write("My own text ...")
print(file3)
file3.close()

# Mode4 a+ append 
file4 = open('module5.txt', 'a+')
file4.write("My own text ...")
print(file4)
file4.seek(0)
print(file4.readline())
file4.close()

import os
os.rename('module55.txt', 'tinkywinky.txt')
os.remove('tinkywinky.txt')


Reading line by line
Holao Edurekans.....

Welcome to the Edureka's internship program Data Science and Machine Learning.

Reading all lines
<_io.TextIOWrapper name='module5.txt' mode='r+' encoding='cp1252'>
<_io.TextIOWrapper name='module5.txt' mode='a' encoding='cp1252'>
<_io.TextIOWrapper name='module5.txt' mode='a+' encoding='cp1252'>
Holao Edurekans.....



In [31]:
# Classes
class car:
    def __init__(self,make,model,color, year):
        self.make=make
        self.model=model
        self.color=color
        self.year = year

    def start(self):
        print(f"The {self.make} {self.model} {self.color} Start BRrroouumm...")
    
    def stop(self):
        print(f"The {self.make} {self.model} {self.color} Stop ...")

car1 = car("BMW", "M3", "Blue", 2024)
car1.start()
car1.stop()

car2 = car("Alpha", "Spider", "Green", 2024)
car2.start()
car2.stop()

The BMW M3 Blue Start BRrroouumm...
The BMW M3 Blue Stop ...
The Alpha Spider Green Start BRrroouumm...
The Alpha Spider Green Stop ...


In [49]:
import numpy as np
# creatin an ndarray 
x = [[1,2,3], [3,4,5], [6,7,8]]
print(type(x))
print(x)
arr = np.array(x)
print(type(arr))
print(type(arr[0][0]))
arr

# ndarray attributes  
print(f'arr.shape: {arr.shape} size array in each diemsion')
print(f'arr.ndim: {arr.ndim}  Number of axes dimension')
print(f'arr.size: {arr.size} Total number of elements')
print(f'arr.dtype: {arr.dtype}')
print(f'arr.itemsize: {arr.itemsize}')

<class 'list'>
[[1, 2, 3], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
arr.shape: (3, 3) size array in each diemsion
arr.ndim: 2  Number of axes dimension
arr.size: 9 Total number of elements
arr.dtype: int64
arr.itemsize: 8


In [50]:
arr2 = np.zeros((5,5))
print(arr2)

arr3 = np.ones((5,5))
print(arr3)

arr4 = np.array([1,2,3,4,5])
print(arr4)

arr5 = arr4.copy()
arr5[0]=0
print(id(arr4))
print(id(arr5))
print(arr4)
print(arr5)

arr6 = np.arange(0,20)
print(arr6)

vector = np.linspace(0,20,5)
print(vector)
print(type(vector))
print(type(vector[0]))
print(vector.ndim)
print(vector.shape)
print(vector.dtype)
print(vector.size)
print(vector.itemsize)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1 2 3 4 5]
2077521514192
2077893956144
[1 2 3 4 5]
[0 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.  5. 10. 15. 20.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
1
(5,)
float64
5
8


In [51]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [53]:
A = np.arange(0,4)
B=np.arange(4,8)
print(A)
print(B)
print(A+B)


[0 1 2 3]
[4 5 6 7]
[ 4  6  8 10]


In [54]:
ary = np.array([1,2,3,5,8])
ary = ary * 6
print (ary[1])

12


In [55]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
print(a)
print(b)
print(c)
c = c*a
print(c)
print (c[2])

[1 2 3 5 8]
[0 3 4 2 1]
[1 5 7 7 9]
[ 1 10 21 35 72]
21


In [57]:
# Arithmetic Operations
a = np.array([1,2,3,5,8])
print(a+4)
print(a*3)

[ 5  6  7  9 12]
[ 3  6  9 15 24]


In [60]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
a*b


array([ 0,  6, 12, 10,  8])

In [67]:
a=np.arange(0,9)
print(a)
b=a.reshape((3,3))
print(b)
c=np.ones((3,3))
print(c)
b*c


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])