In [5]:
import numpy as np
a = np.arange(0,12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
b= a.reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
c = np.ones((3,4))

In [29]:
d = b*c

In [35]:
print(d)
e = d.reshape(4,3)
print(e)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [43]:
f= np.dot(b,d)
print(f)

[[ 20.  23.  26.  29.]
 [ 56.  68.  80.  92.]
 [ 92. 113. 134. 155.]
 [128. 158. 188. 218.]]


In [45]:
#mod function  

a= np.array([1,4,8])
b= np.array([7,8,5])
c = np.mod(a,b)
print(c)

[1 4 3]


In [47]:
#log() logarithm
d=np.log(a)
print(d)

[0.         1.38629436 2.07944154]


In [49]:
print(np.log(b))

[1.94591015 2.07944154 1.60943791]


In [51]:
#bitwise_and

print(np.bitwise_and(a,b))

[1 0 0]


In [53]:
#Broadcasting

#scalar value can broadcast with any array

a = np.array([8,9,7,6,9])
print(a+6)

[14 15 13 12 15]


In [55]:
#2d and 1 d arrays
b = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(a+b)

[[ 9 11 10 10 14]
 [17 17 14 12 14]]


In [61]:
# Mismatched shapes
print(a)
c = np.array([[1],[2],[3]])
print(c)
print(a+c)

[8 9 7 6 9]
[[1]
 [2]
 [3]]
[[ 9 10  8  7 10]
 [10 11  9  8 11]
 [11 12 10  9 12]]


In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a.sum())

45


In [3]:
print(a.min())

1


In [5]:
print(a.max())

9


In [7]:
print(a.mean())

5.0


In [9]:
print(a.std())

2.581988897471611


In [11]:
b = np.array([[True,True,False],[True,True,True]])
print(np.all(b))

False


In [13]:
b = np.array([[True,True,True],[True,True,True]])
print(np.all(b))

True


In [15]:
b = np.array([[True,True,False],[True,True,True]])
print(np.all(b,axis = 1))   #rows

[False  True]


In [17]:
b = np.array([[True,True,False],[True,True,True]])
print(np.all(b,axis = 0))  #columns

[ True  True False]


In [25]:
e = np.array([3,5,5])
print(np.all(e))

True


In [31]:
e = np.array([3,np.nan,5])
print(np.all(e))   #np.nan = 0

True


In [33]:
b = np.array([[True,True,True],[True,True,True]])
print(np.any(b))  #or

True


In [35]:
b = np.array([[True,True,False],[True,True,True]])
print(np.any(b,axis = 1))   #rows

[ True  True]


In [37]:
b = np.array([[True,True,False],[True,True,True]])
print(np.any(b,axis = 0))   #columns

[ True  True  True]


In [41]:
data = np.array([[1+1j, 2],[3,4+0j]])
print(np.iscomplex(data))

[[ True False]
 [False False]]


In [43]:
data = np.array([[1+1j, 2],[3,4+0j]])
print(np.isreal(data))

[[False  True]
 [ True  True]]
