In [1]:
# Module 8: NumPy Array manipulation 

In [9]:
import numpy as np

In [10]:
# Q1 Array manuipulation
a=np.arange(20)
print(a)
b=a.reshape(4,5)
print(b)
c=b.T
print(c)
print(np.dot(b,c))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[  30   80  130  180]
 [  80  255  430  605]
 [ 130  430  730 1030]
 [ 180  605 1030 1455]]


In [11]:
# Q2 Array Manipulation Stacking
d=np.arange(1,5).reshape(2,2)
e=np.arange(5,9).reshape(2,2)
print(f"The first array: {d}")
print(f"The second array: {e}")
h=np.hstack((d,e))
print("hstack ")
print(h)
i=np.vstack((d,e))
print("vstack ")
print(i)
j=i.ravel()
print(j)
np.split(j,4)


The first array: [[1 2]
 [3 4]]
The second array: [[5 6]
 [7 8]]
hstack 
[[1 2 5 6]
 [3 4 7 8]]
vstack 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [5]:
for l in np.nditer(j):
    print(l)
    

1
2
3
4
5
6
7
8


In [6]:
a = [21,22,23, 24, 25, 26,27]
print(a[::-2])
print(a[-2])

[27, 25, 23, 21]
26


In [7]:
import numpy as np 
b=np.arange(1,28,1).reshape(3,3,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [8]:
#fancy indexing 
ind = np.array([[1,2],[5,6]])
print(type(ind), ind)
print(a[ind])

<class 'numpy.ndarray'> [[1 2]
 [5 6]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
#Slicing 
arr=np.arange(20)
print(arr)
s=slice(1,10,2)
print(type(s), s)
print(arr[s])

In [31]:
print(a) 
print(a[::5])
print(a[::-1])
print(a[::-2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5 10 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 17 15 13 11  9  7  5  3  1]


In [46]:
m=np.arange(10).reshape(2,5)
print(m)
print(m[-2:,-2:])
print(m[:,::2])
print(m[::-1,::-1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[3 4]
 [8 9]]
[[0 2 4]
 [5 7 9]]
[[9 8 7 6 5]
 [4 3 2 1 0]]


In [34]:
b=np.array([[1,2],[3,4]])
c=np.array([[5,6],[7,8]])
print(b)
print(c)
print(np.concatenate((b,c), axis=None))
print(np.concatenate((b,c), axis=0)) # vertically
print(np.concatenate((b,c), axis=1)) # Horizontally

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [35]:
d=np.array([[9,9]])
np.concatenate((b,d), axis=0)
np.concatenate((b,d.T), axis=1)
np.sum(b, axis=1)

array([3, 7])

In [36]:
a=np.array((1,2,3))
b=np.array((2,3,4))
print(a)
print(b)
print(type(np.hstack((a,b))))
print(np.hstack((a,b)))

[1 2 3]
[2 3 4]
<class 'numpy.ndarray'>
[1 2 3 2 3 4]


In [37]:
print(type(np.vstack((a,b))))
print(np.vstack((a,b)))

<class 'numpy.ndarray'>
[[1 2 3]
 [2 3 4]]


In [40]:
x=np.arange(9)
print(type(x))
y=np.split(x,3)
print(type(y))
print(y)

<class 'numpy.ndarray'>
<class 'list'>
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [46]:
u=np.arange(16).reshape((4,4))
print("u",u)
[b,c]=np.hsplit(u,2)
print("b", b)
print("c", c)

u [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
c [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [48]:
[b,c]=np.vsplit(u,2)
print("b", b)
print("c", c)

b [[0 1 2 3]
 [4 5 6 7]]
c [[ 8  9 10 11]
 [12 13 14 15]]


In [49]:
# File handling
a=np.array([1,2,3,4,5,6,7,8,9,0])
np.save('data.npy', a) 

b=np.load('data.npy')
print("b", b)

b [1 2 3 4 5 6 7 8 9 0]


In [51]:
b=np.array([1,2,3,4,5,6,7,8,9,1])
c=np.array([1,2,3,4,5,6,7,8,9,2])
d=np.array([1,2,3,4,5,6,7,8,9,3])
e=np.array([1,2,3,4,5,6,7,8,9,4])
np.savez('data.npz', a1=a,b1=b,c1=c,d1=d,e1=e)
f=np.load('data.npz')
print("f", f, type(f)) 


f NpzFile 'data.npz' with keys: a1, b1, c1, d1, e1 <class 'numpy.lib.npyio.NpzFile'>


In [52]:
f['b1']

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [54]:
np.savetxt('data.txt', a, delimiter=',')

In [55]:
l=np.loadtxt('data.txt', delimiter=',')
print('l', l, type(l))

l [1. 2. 3. 4. 5. 6. 7. 8. 9. 0.] <class 'numpy.ndarray'>


In [58]:
np.savetxt('data.csv', a, delimiter=',')
o=np.loadtxt('data.csv', delimiter=',')
print('o', o, type(o))

o [1. 2. 3. 4. 5. 6. 7. 8. 9. 0.] <class 'numpy.ndarray'>


In [57]:
np.savetxt('data.xls', a, delimiter=',')
m=np.loadtxt('data.xls', delimiter=',')
print('m', m, type(m))

m [1. 2. 3. 4. 5. 6. 7. 8. 9. 0.] <class 'numpy.ndarray'>


In [65]:
np.savetxt('data.json', a)
m=np.genfromtxt('data.json')
print('m', m, type(m))

m [1. 2. 3. 4. 5. 6. 7. 8. 9. 0.] <class 'numpy.ndarray'>


In [72]:
data = np.array([[1,np.nan,3],[4,5,6],[7,8,9],[4,np.nan,6]])
np.savetxt('data1.csv',data,delimiter=',')
np.genfromtxt('data1.csv',delimiter=',',missing_values="np.nan",filling_values= 1)

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 4., nan,  6.]])

In [73]:
loaded_data = np.genfromtxt('data1.csv', delimiter=',', missing_values=np.nan, filling_values=1)
# Print the loaded data with NaN replaced
print(loaded_data)

[[ 1. nan  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 4. nan  6.]]


In [76]:
import numpy as np

# Create an array with NaN values
data = np.array([[1, np.nan, 3], [4, 5, 6], [7, 8, 9], [4, np.nan, 6]])

# Save the array to a CSV file
np.savetxt('data1.csv', data, delimiter=',')

# Load the data back, replacing empty fields (NaN) with 1
loaded_data = np.genfromtxt('data1.csv', delimiter=',')

# Replace NaN values with 1
loaded_data = np.nan_to_num(loaded_data, nan=0)

# Print the updated data
print(loaded_data)


[[1. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [4. 0. 6.]]
